name: seamless_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  fluttertoast: ^3.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #f_logs: ^1.2.1

  #https://pub.dev/packages/back_button_interceptor get more detail in this link
  back_button_interceptor: ^4.2.1

  #https://pub.dev/packages/string_validator#-installing-tab-
  string_validator: ^0.1.3

  #https://pub.dev/packages/logger#-installing-tab-
  logger: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-Bold.ttf
        - asset: fonts/Lora-BoldItalic.ttf
        - asset: fonts/Lora-Italic.ttf
        - asset: fonts/Lora-Regular.ttf

    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
